### ISSUE TITLE
mouse over display correct?

### ISSUE THREAD

**Issue by tobiasko** [kusterlab/universal_spectrum_explorer#2]
![Screenshot 2020-09-01 at 15 58 20](https://user-images.githubusercontent.com/12233339/91860543-17e92580-ec6c-11ea-9579-c6a25e2432f6.png)

**Comment by tkschmidt** [comment]
interesting, i will try to recreate it.
```

1117.4895 | 1
988.4469 | 1
901.4149 | 1
800.3672 | 1
703.3145 | 1
574.2719 | 1
477.2191 | 1
376.1714 | 1
263.0874 | 1
148.0604 | 1

```

**Comment by tobiasko** [comment]
I just checked the PRIDE example on the updated version. Now, the mouse over does not show any fragment infos anymore, but y12 is annotated as fragment b2

![Screenshot 2020-09-02 at 12 04 42](https://user-images.githubusercontent.com/12233339/91968195-939ead00-ed14-11ea-922b-cc6a0f6fea5d.png)
I guess there is still some kind of bug in the mouse over code.

**Comment by tkschmidt** [comment]
should be resolved :)
