### ISSUE TITLE
Loading time infinite

### ISSUE THREAD

**Issue by edgarslakis** [kusterlab/universal_spectrum_explorer#27]
I submitted a rather long peptide and 550 rows of spectral data
TSPPPDEGVRGVYGAPIGEITPPEDEGARGVYGGAVAPPPEDEGARGVYGGAIGYPPEDNAPPDGDVRAIYGAPVAVPAENVTTSGN
After hitting Generate chart, it just "Please wait... Loading" forever.
After 4.5h I gave-up
![image](https://user-images.githubusercontent.com/38805016/99383594-62bf2480-28ce-11eb-8c96-e157f28bb39e.png)

I wonder what is a max peptide length?

**Comment by tkschmidt** [comment]
very interesting problem. You tried to compare two experimental spectra?

Prosit is not able to predict such a peptide and is limited to peptides up to a length of 30 aa. 
I will try create better error messages 👍
