### ISSUE TITLE
add source information to plots

### ISSUE THREAD

**Issue by tobiasko** [kusterlab/universal_spectrum_explorer#6]
I was wondering if it would make sense to add some sort of source information to the plots. The pride example shows a PRIDE spetra on top and the Prosit spectra on the bottom. Would be nice to have this information added to the plot. Once you export/save it to disc its not obvious anymore which plots displays what.

![Screenshot 2020-09-02 at 12 12 47](https://user-images.githubusercontent.com/12233339/91969321-3146ac00-ed16-11ea-8ddb-f2d879ca2542.png)

**Comment by tkschmidt** [comment]
Mathias requested that as well. not sure how easy it is but I will figure it out

**Comment by tkschmidt** [comment]
can be closed; done
